site_name: Trailarr Docs
site_url: https://nandyalu.github.io/trailarr
site_description: Trailarr is a simple, lightweight, and easy-to-use media server for your personal media collection.
repo_name: nandyalu/trailarr
repo_url: https://github.com/nandyalu/trailarr
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  logo: https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-512.png
  favicon: https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-48.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - git-revision-date-localized
  # - swagger-ui-tag
  - mkdocs_github_changelog:
        # token: !ENV GITHUB_TOKEN
        # Github token (needs repo scope for private repos, and may be worth setting for public repos due to rate limiting).
        # github_api_url: <url>
        # URL for github api endpoint if not standard github.com (This is not tested on github enterprise server).
        # release_template: <jinja2 str>
        # Jinja2 template string to override the default. 
        # match: '[0-9+].[0-9+].[0-9]+'
        # Regex string for matching the rleease name.
        # autoprocess: True
        # Autoprocess the body for user and issue/pull request links
        enabled: True
        # Enable or disable the plugin.
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/nandyalu/trailarr
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/nandyalu/trailarr
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/trailarr
    - icon: fontawesome/brands/discord
      link: https://discord.gg/KKPr5kQEzQ
nav:
  - Trailarr: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Environment Variables: getting-started/environment-variables.md
    - Volume Mapping: getting-started/volume-mapping.md
    - Docker Compose: getting-started/docker-compose.md
    - Docker Run: getting-started/docker-cli.md
    - Hardware Acceleration: getting-started/hardware-acceleration.md
  - User Guide:
    - Library: user-guide/library.md
    - Tasks: user-guide/tasks.md
    - Logs: user-guide/logs.md
    - General Settings: user-guide/general-settings.md
    - Connections: user-guide/connections.md
    - Profiles:
      - Overview: user-guide/profiles/index.md
      - Settings:
        - General: user-guide/profiles/settings/general.md
        - File: user-guide/profiles/settings/file.md
        - Audio: user-guide/profiles/settings/audio.md
        - Video: user-guide/profiles/settings/video.md
        - Subtitle: user-guide/profiles/settings/subtitle.md
        - Search: user-guide/profiles/settings/search.md
      - Filters: user-guide/profiles/filters.md
      - Examples: user-guide/profiles/examples.md
    - Docker Builder: user-guide/docker-builder.html
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md
  - Release Notes:
    - '2025': release-notes/2025.md
    - '2024': release-notes/2024.md
  - References:
    - Contributing: references/contributing.md
    - Legal Disclaimer: references/legal-disclaimer.md
    - API Docs: references/api-docs/api-docs.html
# extra_javascript:
#   - usage/builder.js