name: Docker Build

on:
  push:
    branches: [ "main" ]
    # Ignore changes to assets, .devcontainer, .github, or .vscode files
    paths-ignore:
      - '**/assets/**'
      - '**/.vscode/**'
      - '**/.github/**'
      - '**/.devcontainer/**'
      - '**/*.md'
      - '**/docs/**'
      - '**/frontend/**'
      - '**/mkdocs.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/assets/**'
      - '**/.vscode/**'
      - '**/.github/**'
      - '**/.devcontainer/**'
      - '**/*.md'
      - '**/docs/**'
      - '**/frontend/**'
      - '**/mkdocs.yml'

jobs:

  build:
    name: Docker Build
    runs-on: ubuntu-latest
    env:
      VER: ${{ github.sha }}-test

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # # Build the Docker image
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag trailarr:${{env.VER}} --build-arg APP_VERSION=${{ env.VER }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
