name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Docker Build
    runs-on: ubuntu-latest
    env:
      VER: ${{ github.sha }}-test

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
        # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag trailarr:${{env.VER}} --build-arg APP_VERSION=${{ env.VER }}
