name: Docker Publish - Nightly

# This is a modified version of the github publish docker image action

on:
  push:
    branches:
      - 'dev'
    # Ignore changes to assets, .devcontainer, .github, or .vscode files
    paths-ignore:
      - '**/assets/**'
      - '**/.vscode/**'
      - '**/.github/**'
      - '**/.devcontainer/**'
      - '**/*.md'
      - '**/docs/**'
      - '**/frontend/**'
      - '**/mkdocs.yml'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**/assets/**'
      - '**/.vscode/**'
      - '**/.github/**'
      - '**/.devcontainer/**'
      - '**/*.md'
      - '**/docs/**'
      - '**/frontend/**'
      - '**/mkdocs.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build_and_push:
    name: Push Docker image (nightly) to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ github.ref_name }}-nightly
